"""
PlatformIO pre-build script. Writes the current git short SHA and dirty flag
into include/git_sha.h so the firmware can display it in the About section.

Invoked automatically via extra_scripts = pre:tools/git_sha_gen.py in
platformio.ini. Fallback to "unknown" if git is not available or we're not
in a git worktree (e.g. building from a downloaded tarball).
"""
import subprocess
from pathlib import Path

Import("env")  # noqa: F821 - PlatformIO injects this

def git_short_sha() -> str:
    try:
        sha = subprocess.check_output(
            ["git", "rev-parse", "--short=7", "HEAD"],
            stderr=subprocess.DEVNULL,
        ).decode().strip()
        dirty = subprocess.call(
            ["git", "diff", "--quiet", "--exit-code"],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        return f"{sha}-dirty" if dirty != 0 else sha
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "unknown"

sha = git_short_sha()
out_path = Path(env.subst("$PROJECT_DIR")) / "include" / "git_sha.h"  # noqa: F821
out_path.parent.mkdir(parents=True, exist_ok=True)

content = (
    "// Auto-generated by tools/git_sha_gen.py. Do not edit.\n"
    "#pragma once\n"
    f'#define GIT_SHA "{sha}"\n'
)
# Only rewrite if changed so we don't trigger pointless rebuilds.
if not out_path.exists() or out_path.read_text() != content:
    out_path.write_text(content)
    print(f"[git_sha_gen] wrote include/git_sha.h with SHA={sha}")
else:
    print(f"[git_sha_gen] include/git_sha.h already up-to-date (SHA={sha})")
