"""
PlatformIO pre-build script: packages web/ui/ into web/littlefs_ui.tar,
then pre-generates the IDF embedding assembly file so PlatformIO's SCons
build finds it ready (avoiding a race with CMake's CUSTOM_COMMAND).

Plain tar (no gzip) so the firmware extracts directly with microtar.

src/storage/ui_provisioner.h is GENERATED — it is gitignored and never
tracked. This script creates it fresh on clean checkout and rewrites it
only when the UI content hash changes (to avoid spurious recompilation).
The base version is derived from FW_VERSION in platformio.ini so there is
no bootstrap dependency on a pre-existing header.
"""

import gzip
import hashlib
import re
import subprocess
import tarfile
import io
import shutil
import sys
from pathlib import Path

Import("env")  # noqa: F821 — injected by PlatformIO

PROJECT_DIR  = Path(env["PROJECT_DIR"])   # noqa: F821
WEB_DIR      = PROJECT_DIR / "web"
UI_DIR       = WEB_DIR / "ui"
OUT_TAR      = WEB_DIR / "littlefs_ui.tar"
PROV_HEADER  = PROJECT_DIR / "src" / "storage" / "ui_provisioner.h"

# IDF tooling paths — use env.subst() to expand SCons $VARIABLES.
BUILD_DIR    = Path(env.subst("$BUILD_DIR"))  # .pio/build/esp32s3
_PKG_DIR     = Path(env.subst("$PROJECT_PACKAGES_DIR"))
CMAKE_SCRIPT = _PKG_DIR / "framework-espidf/tools/cmake/scripts/data_file_embed_asm.cmake"
CMAKE_BIN    = _PKG_DIR / "tool-cmake/bin/cmake"

# Template for the generated header — braces doubled so .format() works.
PROV_HEADER_TEMPLATE = """\
#pragma once

// ── UI Provisioner ───────────────────────────────────────────────────────────
// Checks /lfs/meta/ui_version.txt. If missing or contents != UI_VERSION,
// extracts the embedded littlefs_ui.tar.gz (microtar + IDF miniz) into /lfs/ui/.
// Idempotent: a matching version string is a no-op.
//
// GENERATED FILE — do not edit. Regenerated by web/build_ui.py on every pio run.

namespace storage::ui_provisioner {{

// UI bundle version — SHA-256 content hash of web/ui/ source files.
constexpr const char* UI_VERSION = "{version}";

// Call once during boot after lfs::init(). Extracts if needed.
// Logs extraction progress at INFO level.
void provision_ui_if_needed();

}}  // namespace storage::ui_provisioner
"""


def read_fw_version_base():
    """Return (base, is_dev) parsed from FW_VERSION in platformio.ini.

    '3.1.0-dev.25' → ('3.1.0', True)
    '3.1.0'        → ('3.1.0', False)
    Falls back to ('0.0.0', True) if not found.
    """
    ini_path = PROJECT_DIR / "platformio.ini"
    try:
        text = ini_path.read_text(encoding="utf-8")
        m = re.search(r'-DFW_VERSION=\\"([^\\"]+)\\"', text)
        if m:
            fw = m.group(1)
            dev_m = re.match(r'^(.+)-dev\.\S+$', fw)
            if dev_m:
                return dev_m.group(1), True
            return fw, False
    except OSError:
        pass
    return "0.0.0", True


def read_ui_version():
    """Extract UI_VERSION constant from ui_provisioner.h (after sync_ui_version)."""
    try:
        text = PROV_HEADER.read_text(encoding="utf-8")
        m = re.search(r'UI_VERSION\s*=\s*"([^"]+)"', text)
        if m:
            return m.group(1)
    except OSError:
        pass
    return "unknown"


def compute_ui_content_hash():
    """SHA-256 over all UI source files, stable sorted order.

    Excludes ui_version.txt (derived output) to avoid a chicken-and-egg
    cycle where updating the version would change the hash on the next run.
    """
    h = hashlib.sha256()
    for src in sorted(UI_DIR.rglob("*")):
        if src.is_file() and src.name != "ui_version.txt":
            rel = src.relative_to(UI_DIR).as_posix()
            h.update(rel.encode())
            h.update(b"\0")
            h.update(src.read_bytes())
            h.update(b"\0")
    return h.hexdigest()[:8]


def sync_ui_version():
    """Generate (or regenerate) ui_provisioner.h with the current UI content hash.

    - Fresh checkout (file absent): generates the header from the template.
    - Hash unchanged: skips the write to avoid triggering recompilation.
    - Hash changed: overwrites with new version string.
    - Release build (FW_VERSION has no -dev suffix): uses plain version, no hash.

    The file is gitignored so writing it never dirties the git tree.
    """
    base, is_dev = read_fw_version_base()
    content_hash = compute_ui_content_hash()
    new_version = f"{base}-dev.{content_hash}" if is_dev else base

    if PROV_HEADER.exists():
        existing = PROV_HEADER.read_text(encoding="utf-8")
        m = re.search(r'UI_VERSION\s*=\s*"([^"]+)"', existing)
        if m and m.group(1) == new_version:
            print(f"[build_ui] UI unchanged (hash={content_hash}) — "
                  f"version stays {new_version!r}")
            return

    PROV_HEADER.write_text(PROV_HEADER_TEMPLATE.format(version=new_version),
                           encoding="utf-8")
    print(f"[build_ui] Generated {PROV_HEADER.name} (version={new_version!r})")


def build_tarball():
    if not UI_DIR.exists():
        print(f"[build_ui] ERROR: {UI_DIR} not found", file=sys.stderr)
        env.Exit(1)  # noqa: F821

    ui_version = read_ui_version()
    (UI_DIR / "ui_version.txt").write_text(ui_version, encoding="utf-8")

    # Build plain tar in memory, then write atomically.
    # GNU_FORMAT avoids PAX extended headers (././@PaxHeader type 'x') that
    # Python 3.8+ emits by default; microtar cannot iterate past them.
    #
    # For text assets (JS, CSS, HTML, SVG) we also add a pre-compressed
    # <name>.gz companion so the HTTP server can serve gzip to capable
    # browsers without compressing on the fly.
    COMPRESS_EXTS = {".js", ".css", ".html", ".svg"}
    gz_count = 0
    gz_saved = 0

    buf = io.BytesIO()
    with tarfile.open(fileobj=buf, mode="w", format=tarfile.GNU_FORMAT) as tar:
        for src in sorted(UI_DIR.rglob("*")):
            if src.is_file():
                arcname = src.relative_to(UI_DIR).as_posix()
                tar.add(str(src), arcname=arcname)
                if src.suffix.lower() in COMPRESS_EXTS:
                    data    = src.read_bytes()
                    gz_data = gzip.compress(data, compresslevel=9)
                    if len(gz_data) < len(data):
                        info      = tarfile.TarInfo(name=arcname + ".gz")
                        info.size = len(gz_data)
                        tar.addfile(info, io.BytesIO(gz_data))
                        gz_count += 1
                        gz_saved += len(data) - len(gz_data)

    raw = buf.getvalue()
    tmp = OUT_TAR.with_suffix(".tar.tmp")
    tmp.write_bytes(raw)
    shutil.move(str(tmp), str(OUT_TAR))

    n_files = sum(1 for f in UI_DIR.rglob("*") if f.is_file())
    size_kb  = len(raw) / 1024
    print(f"[build_ui] Packed {n_files} files + {gz_count} .gz companions "
          f"({gz_saved//1024} KB saved by gzip) → {OUT_TAR.name} "
          f"({size_kb:.1f} KB, version={ui_version})")

    return raw


def pre_generate_embed_s(raw_tar_bytes):
    """
    Pre-generate the IDF embedding .S file before SCons tries to compile it.
    PlatformIO's SCons and IDF's CMake CUSTOM_COMMAND both target the same file;
    generating it early avoids the 'source not found' error.
    """
    if not BUILD_DIR or not CMAKE_SCRIPT.exists() or not CMAKE_BIN.exists():
        print("[build_ui] Warning: Cannot pre-generate .S file "
              "(cmake or script not found). Build may fail.", file=sys.stderr)
        return

    embed_s = BUILD_DIR / "littlefs_ui.tar.S"
    embed_s.parent.mkdir(parents=True, exist_ok=True)

    # Always regenerate: mtime comparison can be unreliable when tar and .S
    # are written within the same filesystem timestamp granularity (same second),
    # causing the staleness check to incorrectly skip embedding fresh UI assets.

    try:
        result = subprocess.run(
            [str(CMAKE_BIN),
             "-D", f"DATA_FILE={OUT_TAR}",
             "-D", f"SOURCE_FILE={embed_s}",
             "-D", "FILE_TYPE=TEXT",
             "-P", str(CMAKE_SCRIPT)],
            capture_output=True, text=True, timeout=30
        )
        if result.returncode != 0:
            print(f"[build_ui] Warning: .S generation failed:\n{result.stderr}",
                  file=sys.stderr)
        else:
            print(f"[build_ui] Pre-generated {embed_s.name} "
                  f"({embed_s.stat().st_size} B)")
    except Exception as exc:
        print(f"[build_ui] Warning: .S generation exception: {exc}", file=sys.stderr)


sync_ui_version()
raw = build_tarball()
pre_generate_embed_s(raw)
